// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqx_4eYJHNhq3vDE-ESdwaYEzHGMtREjI',
    appId: '1:548974774100:android:9fb79cde85465f6868aac1',
    messagingSenderId: '548974774100',
    projectId: 'ksquare-learnig',
    databaseURL: 'https://ksquare-learnig-default-rtdb.firebaseio.com',
    storageBucket: 'ksquare-learnig.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAab3THbh0wAZ5nuoZN0VVlYQ4KNMY_mlc',
    appId: '1:548974774100:ios:513fadabc8cf149868aac1',
    messagingSenderId: '548974774100',
    projectId: 'ksquare-learnig',
    databaseURL: 'https://ksquare-learnig-default-rtdb.firebaseio.com',
    storageBucket: 'ksquare-learnig.appspot.com',
    iosClientId: '548974774100-lsmb9huco2bo5e72i6fdi1gcrtnvqpkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.itktask',
  );
}
